name: Deploy docsify branch
on:
  push:
    branches:
      - docsify

jobs:
  deploy-gh-pages:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: put to subdir
      run: |
        mkdir -p docsify/docsify && mv .images dist docs _sidebar.md .nojekyll index.html README.md LICENSE docsify/docsify
        echo '<!DOCTYPE html><html lang="en"><body><a href="./docsify">docsify</a></body></html>' > docsify/index.html

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docsify

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  deploy-vps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
        
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
        ARGS: "-avz --delete"
        EXCLUDE: "/.git/, /.github/"
        SOURCE: "./"
        REMOTE_HOST: "wtfu.site"
        SSH_PRIVATE_KEY: ${{ secrets.DOCS_ACCESS_TOKEN }}
        REMOTE_PORT: ${{ secrets.DOCS_REMOTE_PORT }}
        REMOTE_USER: ${{ secrets.DOCS_USER }}
        TARGET: ${{ secrets.DOCS_TARGET_DIR_DOCSIFY }}